// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scout.Identity.Api.Infrastructure;

#nullable disable

namespace Scout.Identity.Api.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260514000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.Patrulha", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("MonitorId")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("SubmonitorId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("MonitorId");

                b.HasIndex("SubmonitorId");

                b.ToTable("Patrulhas");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.PatrulhaInvite", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CreatedById")
                    .HasColumnType("uuid");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsRevoked")
                    .HasColumnType("boolean");

                b.Property<Guid>("PatrulhaId")
                    .HasColumnType("uuid");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("CreatedById");

                b.HasIndex("PatrulhaId");

                b.HasIndex("Token")
                    .IsUnique();

                b.ToTable("PatrulhaInvites");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.PatrulhaMember", b =>
            {
                b.Property<Guid>("PatrulhaId")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("JoinedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("PatrulhaId", "UserId");

                b.HasIndex("UserId");

                b.ToTable("PatrulhaMembers");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .HasColumnType("text");

                b.Property<string>("GoogleSub")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasFilter("\"Email\" IS NOT NULL");

                b.HasIndex("GoogleSub")
                    .IsUnique()
                    .HasFilter("\"GoogleSub\" IS NOT NULL");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.Patrulha", b =>
            {
                b.HasOne("Scout.Identity.Api.Domain.Entities.User", "Monitor")
                    .WithMany()
                    .HasForeignKey("MonitorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Scout.Identity.Api.Domain.Entities.User", "Submonitor")
                    .WithMany()
                    .HasForeignKey("SubmonitorId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Monitor");

                b.Navigation("Submonitor");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.PatrulhaInvite", b =>
            {
                b.HasOne("Scout.Identity.Api.Domain.Entities.User", "CreatedBy")
                    .WithMany()
                    .HasForeignKey("CreatedById")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Scout.Identity.Api.Domain.Entities.Patrulha", "Patrulha")
                    .WithMany("Invites")
                    .HasForeignKey("PatrulhaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CreatedBy");

                b.Navigation("Patrulha");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.PatrulhaMember", b =>
            {
                b.HasOne("Scout.Identity.Api.Domain.Entities.Patrulha", "Patrulha")
                    .WithMany("Members")
                    .HasForeignKey("PatrulhaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Scout.Identity.Api.Domain.Entities.User", "User")
                    .WithMany("PatrulhaMembers")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patrulha");

                b.Navigation("User");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.Patrulha", b =>
            {
                b.Navigation("Invites");

                b.Navigation("Members");
            });

            modelBuilder.Entity("Scout.Identity.Api.Domain.Entities.User", b =>
            {
                b.Navigation("PatrulhaMembers");
            });
#pragma warning restore 612, 618
        }
    }
}
