// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Scout.Identity.Api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    GoogleSub = table.Column<string>(type: "text", nullable: true),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: true),
                    Role = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Patrulhas",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    MonitorId = table.Column<Guid>(type: "uuid", nullable: false),
                    SubmonitorId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Patrulhas", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Patrulhas_Users_MonitorId",
                        column: x => x.MonitorId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Patrulhas_Users_SubmonitorId",
                        column: x => x.SubmonitorId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PatrulhaInvites",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    PatrulhaId = table.Column<Guid>(type: "uuid", nullable: false),
                    Token = table.Column<string>(type: "text", nullable: false),
                    CreatedById = table.Column<Guid>(type: "uuid", nullable: false),
                    ExpiresAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsRevoked = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PatrulhaInvites", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PatrulhaInvites_Patrulhas_PatrulhaId",
                        column: x => x.PatrulhaId,
                        principalTable: "Patrulhas",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PatrulhaInvites_Users_CreatedById",
                        column: x => x.CreatedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PatrulhaMembers",
                columns: table => new
                {
                    PatrulhaId = table.Column<Guid>(type: "uuid", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    JoinedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PatrulhaMembers", x => new { x.PatrulhaId, x.UserId });
                    table.ForeignKey(
                        name: "FK_PatrulhaMembers_Patrulhas_PatrulhaId",
                        column: x => x.PatrulhaId,
                        principalTable: "Patrulhas",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PatrulhaMembers_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PatrulhaInvites_PatrulhaId",
                table: "PatrulhaInvites",
                column: "PatrulhaId");

            migrationBuilder.CreateIndex(
                name: "IX_PatrulhaInvites_Token",
                table: "PatrulhaInvites",
                column: "Token",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PatrulhaInvites_CreatedById",
                table: "PatrulhaInvites",
                column: "CreatedById");

            migrationBuilder.CreateIndex(
                name: "IX_Patrulhas_MonitorId",
                table: "Patrulhas",
                column: "MonitorId");

            migrationBuilder.CreateIndex(
                name: "IX_Patrulhas_SubmonitorId",
                table: "Patrulhas",
                column: "SubmonitorId");

            migrationBuilder.CreateIndex(
                name: "IX_PatrulhaMembers_UserId",
                table: "PatrulhaMembers",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Users_Email",
                table: "Users",
                column: "Email",
                unique: true,
                filter: "\"Email\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Users_GoogleSub",
                table: "Users",
                column: "GoogleSub",
                unique: true,
                filter: "\"GoogleSub\" IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PatrulhaInvites");

            migrationBuilder.DropTable(
                name: "PatrulhaMembers");

            migrationBuilder.DropTable(
                name: "Patrulhas");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
