// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scout.Location.Api.Infrastructure;

#nullable disable

namespace Scout.Location.Api.Migrations
{
    [DbContext(typeof(LocationDbContext))]
    partial class LocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.UseIdentityByDefaultColumns();

            modelBuilder.Entity("Scout.Location.Api.Domain.Entities.UserLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("real");

                    b.Property<float?>("Altitude")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_UserLocations_EventId");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("IX_UserLocations_RecordedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserLocations_UserId");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_UserLocations_Latitude_Longitude");

                    b.HasIndex("UserId", "EventId")
                        .HasDatabaseName("IX_UserLocations_UserId_EventId");

                    b.ToTable("UserLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
